metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

processors:
  - add_cloud_metadata: ~

logging.level: debug
logging.selectors: ["module","nginx.stubstatus"]

setup.kibana.space.id: elastic-stack-hands-on

# 接続先、認証情報は cloud.id, cloud.auth で設定しているのでここでは不要
output.elasticsearch:
